---
- hosts: local
  roles:
    - myca-db
  tags:
    - db-init
#---
- hosts: local
  roles:
    - myca-wordpress
  tags:
    - wp-init
#---
- hosts: local
  roles:
    - myca-proxy
  tags:
    - proxy
#---
- hosts: local
  roles:
    - myca-cert
  tags:
    - cert
#---
- hosts: local
  roles:
    - init
  tags:
    - all
