---
- name: Update default site config file
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - { src: x, dest: y }

- name: Init Webserver container
  command: docker compose restart webserver
  args:
    chdir: /home/rocky/moji/myca/Word-Press-Demo/

